# /////////////////////////////////////////////////////////////
#                   Mapeamento de externalId
# /////////////////////////////////////////////////////////////
MAPPER_CURSOS_EXTERNOID = {
    "administracao": "G_ADM",
    "biomedicina": "G_BIOMED",
    "ciencia da computacao": "G_CC",
    "ciencias biologicas": "G_CB",
    "ciencias contabeis": "G_CC",
    "educacao fisica bacharelado": "G_EFB",
    "educacao fisica licenciatura": "G_EFL",
    "engenharia de producao": "G_EP",
    "engenharia eletrica": "G_EE",
    "engenharia mecanica": "G_EM",
    "farmacia": "G_FARM",
    "fisioterapia": "G_FISIO",
    "geografia": "G_GEO",
    "historia": "G_HIST",
    "letras portugues literatura": "G_LET",
    "matematica": "G_MAT",
    "pedagogia": "G_PED",
    "semipresencial administracao": "S_ADM",
    "semipresencial biomedicina": "S_BIOMED",
    "semipresencial educacao fisica bacharelado": "S_EFB",
    "semipresencial educacao fisica licenciatura": "S_EFL",
    "semipresencial engenharia de producao": "S_EP",
    "semipresencial engenharia eletrica": "S_EE",
    "semipresencial engenharia mecanica": "S_EM",
    "semipresencial farmacia": "S_FARM",
    "semipresencial nutricao": "S_NUT",
    "servico social": "G_SS",
    "superior de tecnologia em analise e desenvolvimento de sistemas": "G_ADS",
    "superior de tecnologia em comercio exterior": "G_CE",
    "superior de tecnologia em estetica e cosmetica": "G_EST",
    "superior de tecnologia em gestao ambiental": "G_GA",
    "superior de tecnologia em gestao comercial": "G_GC",
    "superior de tecnologia em gestao da producao industrial": "G_GPI",
    "superior de tecnologia em gestao da tecnologia da informacao": "G_GTI",
    "superior de tecnologia em gestao de recursos humanos": "G_RH",
    "superior de tecnologia em gestao financeira": "G_GF",
    "superior de tecnologia em gestao hospitalar": "G_GH",
    "superior de tecnologia em gestao publica": "G_GP",
    "superior de tecnologia em logistica": "G_LOG",
    "superior de tecnologia em marketing": "G_MKT",
    "superior de tecnologia em processos escolares": "G_PE",
    "superior de tecnologia em processos gerenciais": "G_PG",
    "superior de tecnologia em redes de computadores": "G_RC",
    "superior de tecnologia em seguranca publica": "G_SP",
}

# /////////////////////////////////////////////////////////////
#                   Mapeamento de courseTypeId
# /////////////////////////////////////////////////////////////
MAPPER_COURSE_TYPE_ID = {
    "G_ADM": "bachelor",
    "G_BIOMED": "bachelor",
    "G_CC": "bachelor",
    "G_CB": "licentiate",
    "G_CC": "bachelor",
    "G_EFB": "bachelor",
    "G_EFL": "licentiate",
    "G_EP": "bachelor",
    "G_EE": "bachelor",
    "G_EM": "bachelor",
    "G_FARM": "bachelor",
    "G_FISIO": "bachelor",
    "G_GEO": "licentiate",
    "G_HIST": "licentiate",
    "G_LET": "licentiate",
    "G_MAT": "licentiate",
    "G_PED": "licentiate",
    "S_ADM": "bachelor",
    "S_BIOMED": "bachelor",
    "S_EFB": "bachelor",
    "S_EFL": "licentiate",
    "S_EP": "bachelor",
    "S_EE": "bachelor",
    "S_EM": "bachelor",
    "S_FARM": "bachelor",
    "S_NUT": "bachelor",
    "G_SS": "bachelor",
    "G_ADS": "technologist",
    "G_CE": "technologist",
    "G_EST": "technologist",
    "G_GA": "technologist",
    "G_GC": "technologist",
    "G_GPI": "technologist",
    "G_GTI": "technologist",
    "G_RH": "technologist",
    "G_GF": "technologist",
    "G_GH": "technologist",
    "G_GP": "technologist",
    "G_LOG": "technologist",
    "G_MKT": "technologist",
    "G_PE": "technologist",
    "G_PG": "technologist",
    "G_RC": "technologist",
    "G_SP": "technologist",
}
